### ISSUE TITLE
add startOfDay and endOfDay functions

### ISSUE THREAD

**Issue by evangilo** [js-sdk/js-sdk-calendar#3]

**Comment by diasbruno** [comment]
Sounds good. Any suggestions on how we can implement this?

**Comment by evangilo** [comment]
I've opened a PR: https://github.com/js-sdk/js-sdk-calendar/pull/5

**Comment by diasbruno** [comment]
Now, let's see if the [builder](https://github.com/js-sdk/builder) works.

**Comment by diasbruno** [comment]
It looks like it worked!

**Comment by diasbruno** [comment]
Released `0.4.1`.
